repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.1.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        args: ['--config', 'eslint.config.cjs', '--no-ignore']  # Specify the path to your ESLint config file
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]